### ISSUE TITLE
Missing files causing an unusable plugin 

### ISSUE THREAD

**Issue by danevron** [airbrake/airbrake-js#147]
After installing using npm, errors are raised on the client.js file:

    Cannot find module './internal/compat'
    Cannot find module './processors/stack'

It looks like the files are missing. only files are:
/dist/client.js
/dist/instrumentation/jquery.js

looking at `package.json`
```json
  "files": [
    "dist/client.js",
    "dist/instrumentation/jquery.js",
    "LICENSE"
  ],
```
 
This actually makes the notifier unusable.
I might be missing something, help will be much appreciated.

**Comment by vmihailenco** [comment]
How do you include/use the notifier? We have 2 examples at https://github.com/airbrake/airbrake-js/tree/master/examples for RequireJS and script/window. I just verified that both of them work as intended.

**Comment by danevron** [comment]
Using [browserify](http://browserify.org/).
Sorry for not mentioning that.

**Comment by vmihailenco** [comment]
@danevron thanks for reporting. Hopefully I fixed the issue and added example for Browserify: https://github.com/airbrake/airbrake-js/tree/master/examples/browserify. You will need 0.5.0-alpha version to make it work. Let me know if there is anything that I can improve or fix, because I almost don't have any experience with packaging JS code. Then I will release stable version.

**Comment by danevron** [comment]
I can require it now, thanks.
Now I only need to understand how to use it.
Maybe you can help, Before I was using this code to load airBrake as `airbrake_loader.js` file:

```
do (window) ->
  # Airbrake shim that stores exceptions until Airbrake notifier is loaded.
  window.Airbrake = []
  # Registers console reporter when notifier is ready.
  Airbrake.onload = ->
    Airbrake.addReporter Airbrake.consoleReporter

  loadAirbrakeNotifier = ->
    script = document.createElement('script')
    sibling = document.getElementsByTagName('script')[0]
    script.src = 'https://ssljscdn.airbrake.io/0.3/airbrake.min.js'
    script.async = true
    sibling.parentNode.insertBefore script, sibling

  if window.addEventListener
    window.addEventListener 'load', loadAirbrakeNotifier, false
  else
    window.attachEvent 'onload', loadAirbrakeNotifier
```

I added the above script to the head element. This way I could load the airbrake code async (from the CDN) and still have Airbrake object to push to (as an array).
Also, I could pass the needed keys as data attributes in the script as followed:
```
<script data-airbrake-project-id="xxx" data-airbrake-project-key="xxx" data-airbrake-environment-name="production" src='/js/airbrake_loader.js'></script>
```

I'm not sure how to change the code and still keep the async feature.
Again, help will be appreciated.

**Comment by vmihailenco** [comment]
Why do you need async load if you include (require) Airbrake notifier into your application? I don't follow.

>Also, I could pass the needed keys as data attributes in the script as followed:

That trick was needed, because code was loaded asynchronously. Now you can set project_id/API key naturally (https://github.com/airbrake/airbrake-js/blob/master/examples/browserify/app.js#L4):

```
var airbrake = new AirbrakeClient({projectId: 1, projectKey: 'abc'});
```

**Comment by danevron** [comment]
Well I was under the impression that this trick will load my application faster because the code that needs to be synchronously loaded (my application) will be smaller (without the AirBrake code).

The reason for us to change the integration was that we can't get source mapping to work with airBrake, I was thinking to try the newer code to see if it's a version issue.

BTW - We use your product in the Rails backend which is a great help to us, but in the front end it's practically useless without source mapping. This was the motivation for re integration.

**Comment by vmihailenco** [comment]
>Well I was under the impression that this trick will load my application faster because the code that needs to be synchronously loaded (my application) will be smaller (without the AirBrake code).

I believe you will notice anything if you add ~5kb of Airbrake notifier code to your app.min.js file, which is usually >200-300 kb.

>we can't get source mapping to work with airBrake, 

Common mistake is that sourcemap file is not publicly available via HTTP to be downloaded by Airbrake backend, e.g.
- you test integration locally
- source map is not uploaded with minified JS file

I will try to make readme clearer.

**Comment by vmihailenco** [comment]
Added few words in https://github.com/airbrake/airbrake-js/pull/150

**Comment by danevron** [comment]
I guess you have a point with the size of the file.

Since our app is available only via HTTPS (including the map file), I guess this is the problem. Is there a way to make it work via HTTPS?

**Comment by danevron** [comment]
Never mind, Found my mistake, I guess I belong with the common mistakes section.
Thanks for helping.

**Comment by vmihailenco** [comment]
Thank you! Let me know if you have any ideas how to improve docs and/or packaging. Such feedback is very helpful.
